`use strict`
export const lang = {
    "langs": {
        "ar": "العربية",
        "en": "English",
        "fr": "Français"
    },
    "indice": {
        "ar": 0,
        "en": 1,
        "fr": 2
    },
    direction:[1,0,0],
    "trans": {
        "language": ["اللغة", "Language", "Langue"],
        "account": ["الحساب", "Account", "Compte"],
        "settings": ["الإعدادات", "Settings", "Paramètres"],
        "about": ["حول", "About", "A propos"],
        "analytics": ["", "Analytics", ""],
        "postProject": ["", "Post Project", ""],
        "bidProject": ["", "Bid", ""],
        "service": ["الخدمة", "Service", "Service"],
        "services": ["الخدمات", "Services", "Services"],
        "signIn": ["", "Sign In", ""],
        "signUp": ["", "Sign Up", ""],
        "welcome": ["", "Welcome", ""],
        "username": ["", "Username", ""],
        "profile": ["", "Profile", ""],
        "projects": ["", "Projects", ""],
        "signOut": ["", "Sign Out", ""],
        "dashboard": ["", "Dashboard", ""],
        "cancel": ["", "Cancel", ""],
        "saveChanges": ["", "Save Changes", ""],
        "save": ["", "Save", ""],
        "saveAs": ["", "Save as", ""],
        "update": ["", "Update", ""],
        "close": ["", "Close", ""],
        "open": ["", "Open", ""],
        "title": ["", "", ""],
        "findPerfectFreelancer": ["", "Find the perfect freelancer for your project", ""],
        "connectBody": ["", "Connect with skilled professionals who deliver quality work on time, every time.", ""],
        "learnMore": ["", "Learn More", ""],
        "freelancer": ["", "Freelancer", ""],
        "joinUsNow": ["", "Join Us Now", ""],
        "login": ["", "Login", ""],
        "theme": ["", "Theme", ""],
        "fontSize": ["", "Font Size", ""],
        "color": ["", "Color", ""],
        "deactivateAccount": ["", "Deactivate Account", ""],
        "deleteAccount": ["", "Delete Account", ""],
        "password": ["", "Password", ""],
        "emailUsername": ["", "Username or Email", ""],
        "messages": ["", "Messages", ""],
        "submit": ["", "Submit", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "home": ["", "Home", ""],
        "findJobs": ["", "Find Jobs", ""],
        "findFreelancers": ["", "Find Professionals", ""],
        "bugBounty": ["", "Bug Bounty", ""],
        "howItWorks": ["", "How It Works?", ""],
        "": ["", "", ""],
        "helpSupport": ["", "Help & Support", ""],
        "notifications": ["", "Notifications", ""],
        "general": ["", "General", ""],
        "payment": ["", "Payment", ""],
        "inviteFriend": ["", "Invite Friend", ""],
        "firstName": ["", "First Name", ""],
        "lastName": ["", "Last Name", ""],
        "address": ["", "Address", ""],
        "city": ["", "City", ""],
        "country": ["", "Country", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "a1": ["", "Where AI Meets Hardware Design", ""],
        "exploreMarket": ["", "Explore Marketplace", ""],
        "tryAITool": ["", "Try AI Tool", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "hireFreelancer": ["", "Hire a Freelancer", ""],
        "joinFreelancer": ["", "Join as a Freelancer", ""],
        "aiSearchBody": ["", "What service are you looking for today?", ""],
        "exploreCategs": ["", "Explore Categories", ""],
        "exploreCategsBody": ["", "Browse through the most in-demand services and find the perfect match for your project needs.", ""],
        "featuredFreelancers": ["", "Featured Freelancers", ""],
        "discoverTopBody": ["", "Discover top-rated professionals ready to help with your project", ""],
        "": ["", "", ""],
        "footerWord": ["", "Connecting talented professionals with amazing clients worldwide since 2025.", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "trendProjs": ["", "Trending Projects", ""],
        "browseProjs": ["", "Browse the most in-demand projects that clients are looking to hire for", ""],
        "howRobolecs": ["", "How Robolec Works", ""],
        "howRobolecsWord": ["", "We make it easy to find talent and get work done. Here's how our platform connects clients with freelancers.", ""],
        "howRobolecsBtn": ["", "Learn More About Our Process", ""],
        "howRobolecsBody": ["", "We connect talented freelancers with amazing clients. Our platform makes it easy to find talent, collaborate on projects, and get work done.", ""],
        "whatTheySay": ["", "What Our Users Say", ""],
        "whatTheySayWord": ["", "Hear from clients and freelancers who have found success on our platform", ""],
        "readyStart": ["", "Ready to get started?", ""],
        "readyStartWord": ["", "Join thousands of clients and freelancers who are already using Robolec to connect, collaborate, and create amazing work together.", ""],
        "joinRobolecers": ["", "Join Robolecers, and push yourself beyond limits", ""],
        "": ["", "", ""],
        "allRightsReserved": ["", "© 2025 Robolec. All rights reserved.", ""],
        "privacyPolicy": ["", "Privacy Policy", ""],
        "termsService": ["", "Terms of Service", ""],
        "cookiePolicy": ["", "Cookie Policy", ""],
        "": ["", "", ""],
        "simplePowerful": ["", "A Simple, Powerful Process", ""],
        "simplePowerfulBody": ["", "Whether you're hiring or looking for work, our streamlined process helps you achieve your goals quickly and efficiently", ""],
        "simplePowerfulOne": ["", "1. Post a Project", ""],
        "simplePowerfulTwo": ["", "2. Review Proposals", ""],
        "simplePowerfulThree": ["", "3. Collaborate & Pay", ""],
        "simplePowerfulOneBody": ["", "Create a detailed project brief outlining your requirements, timeline, and budget. The more specific you are, the better matches you'll find.", ""],
        "simplePowerfulTwoBody": ["", "Receive proposals from qualified freelancers. Review their profiles, portfolios, and ratings to find the perfect match for your project.", ""],
        "simplePowerfulThreeBody": ["", "Work with your chosen freelancer through our secure platform. Release payment only when you're completely satisfied with the delivered work.", ""],
        "findPerfectTalent": ["", "Find the Perfect Talent for Your Project", ""],
        "findPerfectTalentBody": ["", "Access our global pool of professional freelancers and get your projects done efficiently and affordably", ""],
        "findPerfectTalentOne": ["", "Access Top Talent", ""],
        "findPerfectTalentTwo": ["", "Secure Payments", ""],
        "findPerfectTalentThree": ["", "Quality Assurance", ""],
        "findPerfectTalentOneBody": ["", "Connect with skilled professionals across various categories including web development, design, writing, marketing, and more.", ""],
        "findPerfectTalentTwoBody": ["", "Our escrow payment system ensures you only pay for work that meets your expectations. Release funds when you're satisfied.", ""],
        "findPerfectTalentThreeBody": ["", "Our rating system and verified reviews help you identify top performers. We also offer dispute resolution if issues arise.", ""],
        "findWorkGrow": ["", "Find Work and Grow Your Business", ""],
        "findWorkGrowBody": ["", "Discover opportunities that match your skills and build a sustainable freelance career on our platform", ""],
        "findWorkGrowOne": ["", "Find Relevant Projects", ""],
        "findWorkGrowTwo": ["", "Get Paid Reliably", ""],
        "findWorkGrowThree": ["", "Build Your Reputation", ""],
        "findWorkGrowOneBody": ["", "Browse projects that match your skills and experience. Our smart matching system helps you discover opportunities you're most qualified for.", ""],
        "findWorkGrowTwoBody": ["", "Our secure payment system ensures you get paid for your work. Set your own rates and receive payments promptly.", ""],
        "findWorkGrowThreeBody": ["", "Showcase your portfolio, collect reviews, and build a strong reputation. Higher ratings lead to more opportunities and better rates.", ""],
        "successStories": ["", "Success Stories", ""],
        "successStoriesBody": ["", "See how Robolec has helped businesses and freelancers achieve their goals", ""],
        "frequencyAsked": ["", "Frequently Asked Questions", ""],
        "frequencyAskedBody": ["", "Find answers to common questions about using Robolec", ""],
        "stillQuestions": ["", "Still have questions?", ""],
        "contactSupport": ["", "Contact Support", ""],
        "searchHelp": ["", "Search help articles...", ""],
        "contactSupport": ["", "Contact Support", ""],
        "subject": ["", "Subject", ""],
        "description": ["", "Description", ""],
        "priority": ["", "Priority", ""],
        "attachements": ["", "Attachements", ""],
        "balance": ["", "Balance", ""],
        "": ["", "", ""],
        "dzd": ["", "DZD", "DA"],
        "usd": ["", "USD", ""],
        "eur": ["", "EUR", ""],
        "": ["", "", ""],
        "createYourProfile": ["", "Create Your Profile", ""],
        "createAnAccount": ["", "Create An Account", ""],
        "browseProjects": ["", "Browse Projects", ""],
        "forClients": ["", "FOR CLIENTS", ""],
        "forFreelancers": ["", "FOR FREELANCERS", ""],
        "": ["", "", ""],
        "all": ["", "All", ""],
        "lowToUrgent": ["", "Low,Medium,High,Urgent", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "viewAll": ["", "View All", ""],
        "viewProfile": ["", "View Profile", ""],
        "viewDetails": ["", "View Details", ""],
        "recentNotifications": ["", "Recent Notifications", ""],
        "discoverOpportunity": ["", "Discover Your Next Opportunity", ""],
        "searchProjectsBy": ["", "Search Project by title, company or keyword", ""],
        "fullTime": ["", "Full Time", ""],
        "partTime": ["", "Part Time", ""],
        "contract": ["", "Contract", ""],
        "freelance": ["", "Freelance", ""],
        "nationalId": ["", "National ID", ""],
        "low": ["", "Low", ""],
        "medium": ["", "Medium", ""],
        "high": ["", "High", ""],
        "urgent": ["", "Urgent", ""],
        "latest": ["", "Latest", ""],
        "oldest": ["", "Oldest", ""],
        "lowestPrice": ["", "Lowest Price", ""],
        "highestPrice": ["", "Highest Price", ""],
        "fewestBids": ["", "Fewest Bids", ""],
        "mostBids": ["", "Most Bids", ""],
        "applyNow": ["", "Apply Now", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""],
        "": ["", "", ""]
    },
    "default": "en",
    "current": 1
}